apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: entity-feedback-demo
  description: Feedback test demo
   
spec:
  type: service
  lifecycle: production
  owner: User:default/padmapriya-vn
